import {createSlice} from '@reduxjs/toolkit';


//createSlice is a function that accepts a slice name, an initial state and an object full of reducer functions
const authSlice = createSlice({ //must use these keys (can't change their names)
    name: "authenticator", //indicates which slice of state we are managing
    initialState: {isLoggedIn: false},
    reducers: {
      logIn: (state, action)=>{state.isLoggedIn = true},
      logOut: (state, action)=>{state.isLoggedIn = false}
    }
});

export default authSlice.reducer; //the reducer function generated by createSlice
export const {logIn, logOut} = authSlice.actions; //automatically generated action creators based on the