import {createSlice} from '@reduxjs/toolkit';

const initState = {
  show: true
};

//createSlice is a function that accepts a slice name, an initial state and an object full of reducer functions
const authSlice = createSlice({ //must use these keys (can't change their names)
    name: "authenticator", //indicates which slice of state we are managing
    initialState: initState,
    reducers: {
      toggle: (state, action)=>{state.show = !state.show}
    }
});

export default authSlice.reducer; //the reducer function generated by createSlice
export const {toggle} = authSlice.actions; //automatically generated action creators based on the